obtenerSucursalPorFolio = (folio = 'FA') => {
    const folioSucursal = {
        FA:'1002 DULCERIA G32',
        FB:'1002 DULCERIA G32',
        FC:'1102 DULCERIA MADERO',
        FCP:'1102 DULCERIA MADERO',
        FD:'1000 CEDIS',
        FE:'1004 DULCERIA AC',
        FEP:'1004 DULCERIA AC',
        FG:'1006 DULCERIA TURCIO',
        FGN:'1006 DULCERIA TURCIO',
        FGP:'1006 DULCERIA TURCIO',
        FHP:'EL GIRASOL (GORDOA SUCURSAL)',
        FJ:'1201 DULCERIA BENITO JUAREZ',
        FJP:'1201 DULCERIA BENITO JUAREZ',
        FK:'1005 CEREALES PAEZ',
        FKP:'1005 CEREALES PAEZ',
        FL:'1012 RUTA GUZMAN',
        FLN:'1012 RUTA GUZMAN,RUTA FORANEA',
        FM:'1012 RUTA GUZMAN,RUTA FORANEA',
        FN:'1202 CEREALES COLINAS',
        FNB:'1002 DULCERIA G32',
        FNC:'1102 DULCERIA MADERO,COLIMA',
        FNE:'1004 DULCERIA AC,ALBERTO CARDENAS',
        FNJ:'1201 DULCERIA BENITO JUAREZ,VILLA',
        FNN:'1202 CEREALES COLINAS,VILLA COLINA DEL REY',
        FNO:'1203 DESECHABLES RCHAVEZ,DESECHABLES RCHAVEZ  ',
        FO:'1204 RUTA VILLA',
        FPA:'1003 REPOSTERIA G10',
        FPB:'1002 DULCERIA G32',
        FPN:'1202 CEREALES COLINAS',
        FQ:'1103 REPOSTERIA MADERO',
        FQP:'1103 REPOSTERIA MADERO'
    }
    return folioSucursal[folio] || 'Sin definir'
}

module.exports = {
    obtenerSucursalPorFolio
}
