const QUERY = {};

/*Consulta las existencias, costo y folios pendientes de compras de FORECAST */
QUERY.EXISTENCIAS =(provId)  => { return `SELECT * FROM P_GET_JEC_MICROSIPFRKID (${ provId })`;
}

/*Borra la relacion de articulo proveedor de sistema FORECAST */
QUERY.BORRA_PROV_ART = (provId) => {
    return `DELETE  FROM XT_PROARTFORECAST WHERE PROVEEDORID=${ provId }`
}

/* Inserta la relación de artículo proveedor de sistema FORECAST */
QUERY.INSERTA_PROV_ART = (proveedorId,claveArticulo)=>{    
  return `
  INSERT INTO XT_PROARTFORECAST (PROVEEDORID, CLAVE_ARTICULO) 
  VALUES (${ proveedorId }, '${ claveArticulo }')`;
}

//QUERY.EXISTENCIAS = `SELECT * FROM P_GET_JEC_MICROSIP WHERE CLAVE_ARTICULO IN ( '100109', '100125', '100119', '100113', '100155' )`;

QUERY.GET_SUPPLIER_BY_ID = ( id ) => {
    return `
        SELECT 
        A.*,
        B.CLAVE_PROV
    FROM 
        PROVEEDORES A 
    LEFT JOIN 
        GET_CLAVE_PROV(A.PROVEEDOR_ID) B 
    ON 
        (B.PROVEEDOR_ID = A.PROVEEDOR_ID) 
    WHERE 
        A.PROVEEDOR_ID = ${ id }`;
} 

QUERY.GET_SUPPLIER_BY_NAME = ( name ) => {
    return `
    SELECT 
        A.*,
        B.CLAVE_PROV
    FROM 
        PROVEEDORES A 
    LEFT JOIN 
        GET_CLAVE_PROV(A.PROVEEDOR_ID) B 
    ON 
        (B.PROVEEDOR_ID = A.PROVEEDOR_ID) 
    WHERE 
        A.NOMBRE = '${ name }'`;
} 

QUERY.GET_NEXT_INVOICE = `
    SELECT 
        CONSECUTIVO 
    FROM 
        FOLIOS_COMPRAS 
    WHERE 
        TIPO_DOCTO = 'O'
`;

QUERY.GET_NEXT_DOCTO_CM_ID = `
    SELECT 
        MAX( D.DOCTO_CM_ID ) +1 AS DOCTO_CM_ID
    FROM 
        DOCTOS_CM D
`;

QUERY.INSERT_DOCTOS_CM = ( data ) => {
    return `
    INSERT INTO DOCTOS_CM 
        ( DOCTO_CM_ID, TIPO_DOCTO, SUBTIPO_DOCTO, SUCURSAL_ID, FOLIO, FECHA, CLAVE_PROV, PROVEEDOR_ID, FOLIO_PROV, FACTURA_DEV, CONSIG_CM_ID, ALMACEN_ID, PEDIMENTO_ID, MONEDA_ID, TIPO_CAMBIO, TIPO_DSCTO, DSCTO_PCTJE, DSCTO_IMPORTE, ESTATUS, APLICADO, FECHA_ENTREGA, DESCRIPCION, IMPORTE_NETO, FLETES, OTROS_CARGOS, TOTAL_IMPUESTOS, TOTAL_RETENCIONES, GASTOS_ADUANALES, OTROS_GASTOS, FORMA_EMITIDA, CONTABILIZADO, ACREDITAR_CXP, SISTEMA_ORIGEN, COND_PAGO_ID, FECHA_DSCTO_PPAG, PCTJE_DSCTO_PPAG, VIA_EMBARQUE_ID, IMPUESTO_SUSTITUIDO_ID, IMPUESTO_SUSTITUTO_ID, CARGAR_SUN, ENVIADO, FECHA_HORA_ENVIO, EMAIL_ENVIO, TIENE_CFD, USUARIO_CREADOR, FECHA_HORA_CREACION, USUARIO_ULT_MODIF, FECHA_HORA_ULT_MODIF )
    VALUES
        ( ${ data.DOCTO_CM_ID }, 'O', 'N', 848194, '${ data.FOLIO }', '${ data.FECHA }', '${ data.CLAVE_PROV }', ${ data.PROVEEDOR_ID }, NULL, NULL, NULL, 181613, NULL, 1, 1, 'P', 0, 0, 'P', 'S', '${ data.FECHA_ENTREGA }', NULL, ${ data.IMPORTE_NETO }, 0, 0, 0, 0, 0, 0, 'N', 'N', 'N', 'CM', ${ data.COND_PAGO_ID }, NULL, 0, 179011, NULL, NULL, 'S', 'N', NULL, NULL, 'N', '${ data.USER }', '${ data.FECHA_HORA_CREACION }', 'SYSDBA', '${ data.FECHA_HORA_CREACION }' );
    `;
}

QUERY.INSERT_MANY_DOCTOS_CM_DET = ( DOCTO_CM_ID, i, index ) => {
    return `
    INSERT INTO DOCTOS_CM_DET 
        ( DOCTO_CM_DET_ID, DOCTO_CM_ID, CLAVE_ARTICULO, ARTICULO_ID, UNIDADES, UNIDADES_REC_DEV, UNIDADES_A_REC, UMED, CONTENIDO_UMED, PRECIO_UNITARIO, PCTJE_DSCTO, PCTJE_DSCTO_PRO, PCTJE_DSCTO_VOL, PCTJE_DSCTO_PROMO, DSCTO_ART, DSCTO_EXTRA, PRECIO_TOTAL_NETO, PCTJE_ARANCEL, POSICION ) 
    VALUES
        ( -1, ${ DOCTO_CM_ID }, '${ i.CLAVE_ARTICULO }', ${ i.ARTICULO_ID }, ${ i.UNIDADES }, 0, 0, '${ i.UMED }', ${ i.CONTENIDO_UMED }, ${ i.PRECIO_UNITARIO }, 0, 0, 0, 0, 0, 0, ${ i.PRECIO_TOTAL_NETO }, 0, ${ index } );
    `
}

QUERY.UPDATE_NEXT_INVOICE = ( CONSECUTIVO ) => {
    return `
    UPDATE FOLIOS_COMPRAS
        SET CONSECUTIVO = ${ CONSECUTIVO }
    WHERE
        TIPO_DOCTO = 'O'
    `;
}

QUERY.P_GET_JEC_PRV_FILL_RATE_WEB = `
    SELECT 
        * 
    FROM 
        P_GET_JEC_PRV_FILL_RATE_WEB
`;

QUERY.P_GET_JEC_PRV_FILL_RATE_WEB_RANGE = ( START, END ) => {
    return `
    SELECT 
        * 
    FROM 
        P_GET_JEC_PRV_FILL_RATE_WEB( '${ START }', '${ END }' )
    `;
}

QUERY.P_GET_JEC_ARTS_ULT_COST_FULL = ( DATE ) => {
    return `
    SELECT
     CA.CLAVE_ARTICULO,
        UC.COSTO_PROMEDIO
    FROM
        P_GET_JEC_ARTS_ULT_COST_FULL( '${ DATE }', 30 ) UC
    JOIN
        CLAVES_ARTICULOS CA
    ON
        UC.ARTICULO_ID = CA.ARTICULO_ID
    WHERE
        CA.ROL_CLAVE_ART_ID = 17
        AND UC.COSTO_PROMEDIO != 0
    `
}

QUERY.P_GET_JEC_EXISTENCIAS_X_DIA = ( ALMACEN_ID, DATE ) => {
    return `SELECT * FROM P_GET_JEC_EXISTENCIAS_X_DIA( ${ ALMACEN_ID }, '${ DATE }' )`
}

QUERY.P_GET_JEC_DOCTOS_CM_SQL_SERVER = ( DATE, TIPO = 'C' ) => {
    return `SELECT * FROM P_GET_JEC_DOCTOS_CM_SQL_SERVER( '${ DATE }', '${ TIPO }' )`
}

QUERY.GET_JEC_ARTICULOS_PRECIOS = () => {
    return `
    SELECT
        C.CLAVE_ARTICULO,
        ROUND( PRECIO_LISTA, 4) AS  PRECIO_LISTA,
        ROUND( PRECIO_MAYOREO, 4) AS  PRECIO_MAYOREO,
        ROUND( PRECIO_ESPECIAL, 4) AS  PRECIO_ESPECIAL,
        ROUND( PRECIO_TIENDA, 4) AS  PRECIO_TIENDA,
        ROUND( PRECIO_TIENDA_JECOR, 4) AS  PRECIO_TIENDA_JECOR,
        ROUND( PRECIO_MINIMO, 4) AS  PRECIO_MINIMO,
        ROUND( PRECIO_CONSUMO_INTERNO, 4) AS  PRECIO_CONSUMO_INTERNO
    FROM P_GET_JEC_ART_PRICES P
    JOIN CLAVES_ARTICULOS C ON P.ARTICULO_ID = C.ARTICULO_ID
    WHERE C.ROL_CLAVE_ART_ID = 17
    `
}

QUERY.P_GET_JEC_ARTICULOS_PRECIO_LIM = ( LIMIT = 2000 ) => {
    return `SELECT * FROM P_GET_JEC_ARTICULOS_PRECIO_LIM( ${ LIMIT } )`;
}

QUERY.GET_PENDING_RECEIPTS = `
    SELECT A.NOMBRE, D.FECHA, D.FOLIO, P.NOMBRE AS PROVEEDOR, D.IMPORTE_NETO, D.TOTAL_IMPUESTOS, (D.IMPORTE_NETO + D.TOTAL_IMPUESTOS) AS TOTAL
    FROM DOCTOS_CM D
    JOIN PROVEEDORES P ON P.PROVEEDOR_ID = D.PROVEEDOR_ID
    JOIN ALMACENES A ON A.ALMACEN_ID = D.ALMACEN_ID
    WHERE D.TIPO_DOCTO = 'R' AND D.ESTATUS = 'P' AND D.FECHA >= '01.01.2023'
    ORDER BY D.FECHA
`;

QUERY.GET_CLAVES_ARTICULOS_ROL = `
    SELECT C.ARTICULO_ID, C.ROL_CLAVE_ART_ID, REPLACE(C.CLAVE_ARTICULO , '''', '-') AS CLAVE_ARTICULO
    FROM CLAVES_ARTICULOS C
`

module.exports = { QUERY };